ci:
  collect:
    numberOfRuns: 1
    staticDistDir: ./build
    url:
      - http://localhost/
  # assert:
  #   assertions:
  #     categories:performance: off
  #     categories:pwa: off
  upload:
    target: temporary-public-storage
